### ISSUE TITLE
Footer: Inconsistent copyright format from design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#1]
![1](https://cloud.githubusercontent.com/assets/18256652/14972853/47e05404-1113-11e6-9640-8273a501892b.png)

**Comment by bukssaayman** [comment]
Fixed.

**Comment by iteano** [comment]
Still not consistent, missing comma.

![1a](https://cloud.githubusercontent.com/assets/18256652/15241533/280c7aaa-1923-11e6-8095-ca2dc4576b72.png)

**Comment by bukssaayman** [comment]
Fixed. Comma has been added.
