### ISSUE TITLE
General-Breadcrumbs : Please disable the link that directs to its page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#101]
![101](https://cloud.githubusercontent.com/assets/18256652/15278371/60aef954-1b4a-11e6-9e89-9b6f697bc31a.png)

**Comment by bukssaayman** [comment]
Fixed.

**Comment by iteano** [comment]
This also occurs on all main pages and inner pages.

**Comment by bukssaayman** [comment]
Fixed.

**Comment by iteano** [comment]
Still not fix on Purchase Coffee page.

![c](https://cloud.githubusercontent.com/assets/18256652/15379922/23e0e5bc-1da4-11e6-943d-5fa2277e7b1b.png)

**Comment by bukssaayman** [comment]
Fixed.
