### ISSUE TITLE
Product Listing : Please align button.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Community-Pod#43]
![43](https://cloud.githubusercontent.com/assets/18256652/15008998/92a1776c-1216-11e6-97f4-93bc119b842e.png)

**Comment by euveng** [comment]
Fixed.

**Comment by iteano** [comment]
Still not aligned if the product doesn't have price.

![43a](https://cloud.githubusercontent.com/assets/18256652/15242625/d004cb94-1929-11e6-9a3b-6442ba26db2c.png)

**Comment by bukssaayman** [comment]
Fixed.
